restapi_demo/apidemo/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from apidemo import views
from django.contrib.auth import views as auth_views

urlpatterns = [

    #Admin Panel and Index.

    #path('admin/', admin.site.urls),
    path('', views.login_v,name='login_v'),
    #path('api/',include('urls.apidemo')),
    # URLS for REST API

    path('rest_register/', views.Signup,name='rest_register'),  # Registration using REST.
    path('rest_login/', views.LoginView.as_view(), name='rest_login'),       # REST Login.
    path('dash/', include('rest_framework.urls', namespace='rest_framework')),



    # Login,Logout And Registration

    path('user_login/', views.demo_user_login,name='user_login'),
    url(r'^signup/$', views.Signup, name='signup'),
    path('login_v/', views.login_v, name='login_v'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
    path('logout/', views.logout, name='logout'),


    # Reset Password

    url(r'^password_reset/$', auth_views.PasswordResetView.as_view(), name='password_reset'),
    url(r'^password_reset/done/$', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),



    # Upload Profile Pic
    path('upload_profile/', views.upload_profile, name='upload_profile'),
    path('open_upload_form/', views.open_upload_form, name='open_upload_form'),
    path('profile_page/', views.profile_page, name='profile_page'),


    #Base Template

    path('base/', views.base, name='base'),


    #crop profile picture

    path('crop/', views.crop, name='crop'),
    path('photo_list/', views.photo_list, name='photo_list'),


    path('demo/',views.demo,name='demo'),


    # CRUD Operations

    path('addnote/', views.AddNote.as_view(),name='addnote'),
    #deletenote
    path('delete/<int:id>/',views.deleteN, name='deleteN'),
    #getnotes
    #move_to_trash
    path('move_to_trash/<int:id>/',views.trash, name='move_to_trash'),

    path('getnotes/', views.getnotes.as_view(), name='getnotes'),
    #updatenote
    path('updatenote/<int:pk>/', views.updatenote.as_view(),name='updatenote'),
    path('updateform/<int:pk>/', views.updateform, name='updateform'),

    #updateNotes
    path('updateNotes/<int:pk>/', views.updateNotes, name='updateNotes'),


    #pin_unpin
    path('pin_unpin/<int:pk>/', views.pin_unpin, name='pin_unpin'),


    #trash
    path('trash/<int:pk>/', views.trash, name='trash'),
    #view_trash
    path('view_trash/', views.view_trash.as_view(), name='view_trash'),


    #delete_forever
    path('delete_forever/<int:pk>/', views.delete_forever, name='delete_forever'),

    #is_archived
    path('is_archived/<int:pk>/', views.is_archived, name='is_archived'),
    #View_is_archived
    path('View_is_archived/', views.View_is_archived.as_view(), name='View_is_archived'),


    # Labels
    #add_labels
    path('add_labels/<int:pk>/', views.add_labels, name='add_labels'),
    #map_labels
    path('map_labels/', views.map_labels, name='map_labels'),
    #delete_label
    path('delete_label/<int:pk>/', views.delete_label, name='delete_label'),
    #view_notes_for_each_label
    path('view_notes_for_each_label/<int:pk>/', views.view_notes_for_each_label, name='view_notes_for_each_label'),
    #copy_note
    path('copy_note/<int:pk>/', views.copy_note, name='copy_note'),
    #remove_labels
    path('remove_labels/<int:id>/<int:key>/', views.remove_labels, name='remove_labels'),


    # <a href="{% url 'remove_labels' l.label_id  user.id i.id %}" >&times;</a>

    # Search
    path('search/',views.search,name='search'),

    #reminder
    path('reminder/', views.reminder, name='reminder'),
    path('View_reminder/', views.View_reminder.as_view(), name='View_reminder'),


    #Update
    path('Update/<int:pk>/', views.Update.as_view(), name='Update'),
    #View_reminder



    #change_color
    path('change_color/<int:pk>/', views.change_color, name='change_color'),


    #auto_delete_archive
    path('auto_delete_archive/', views.auto_delete_archive, name='auto_delete_archive'),

    #invite
    path('invite/', views.invite, name='invite'),

    #delete_from_s3
    path('delete_from_s3/', views.delete_from_s3, name='delete_from_s3'),
]

restapi_demo/restapi_demo/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from rest_framework.urlpatterns import format_suffix_patterns
#from restapi_demo.apidemo import views
from apidemo import views
from django.contrib.auth import views as auth_views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index,name='index'),
    path('rest_register/', views.Signup,name='rest_register'),  # Registration using REST.
    path('rest_login/', views.LoginView.as_view(),name='rest_login'),       # REST Login.
    path('dash/',include('rest_framework.urls', namespace='rest_framework')),

    path('user_login/', views.demo_user_login,name='user_login'),


    url(r'^signup/$', views.Signup, name='signup'),
    path('login_v/', views.login_v, name='login_v'),
#    path('login/', views.user_login,name='user_login'),

    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),

    url(r'^password_reset/$', auth_views.PasswordResetView.as_view(), name='password_reset'),
    url(r'^password_reset/done/$', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    #LoginDemoWithRest

    #upload_profile
    path('upload_profile/', views.upload_profile, name='upload_profile'),
    #open_upload_form
    #simple_upload
    path('open_upload_form/', views.open_upload_form, name='open_upload_form'),
    #path('form_file/', views.form_file, name='form_file'),
    #profile_page
    path('profile_page/', views.profile_page, name='profile_page'),
]

restapi_demo/apidemo/models.py
"""
* Purpose:  Models (Database Interaction)

* @author: Nikhil Lad
* @version: 3.7
* @since: 01-1-2019

"""
from django.contrib.auth.models import User
from django.db import models
from django.core.validators import FileExtensionValidator

class RestRegistration(models.Model):       # Registration model for REST API.
    username=models.CharField(max_length=20)
    password = models.CharField(max_length=20)
    confirm_password = models.CharField(max_length=20,default='none')
    email=models.CharField(max_length=30)


    def __str__(self):
        return self.username


    def check_uname(self):
        return self.username



class Photo(models.Model):              # Model For profile picture
    file = models.ImageField(validators=[FileExtensionValidator(allowed_extensions=['jpeg'])])
    description = models.CharField(max_length=255, blank=True)
    uploaded_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'photo'
        verbose_name_plural = 'photos'


class Notes(models.Model):      # Model to Create Notes.
    title = models.CharField(max_length=150,default=None)
    description = models.TextField()
    created_time = models.DateTimeField(auto_now_add=True, null=True)
    reminder = models.CharField(default=None, null=True,max_length=25)
    #reminder = models.DateField(default=None, null=True)
    is_archived = models.BooleanField(default=False)
    is_deleted = models.BooleanField(default=False)
    for_color = models.CharField(default=None, max_length=50, blank=True, null=True)
    image = models.ImageField(default=None, null=True)
    trash = models.BooleanField(default=False)
    is_pinned = models.NullBooleanField(blank=True, null=True, default=None)
    label = models.CharField(max_length=50,default=None,null=True)
    collaborate = models.ManyToManyField(User, null=True, blank=True, related_name='collaborated_user')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='owner', null=True, blank=True)
    archive_time= models.DateTimeField(blank=True,null=True)
    trash_time=models.DateTimeField(blank=True,null=True)

    def __str__(self):          # string Representation for model.
        return self.title


class Labels(models.Model):
    label_name=models.CharField(max_length=50)
    created_time= models.DateTimeField(auto_now_add=True,null=True)
    user= models.ForeignKey(User, on_delete=models.CASCADE,null=True, blank=True)

    def __str__(self):
        return self.label_name


class Map_labels(models.Model):
    label_id=models.ForeignKey(Labels,null=True,blank=True,on_delete=models.CASCADE)
    user=models.ForeignKey(User, on_delete=models.CASCADE,null=True, blank=True)
    created_time = models.DateTimeField(auto_now_add=True, null=True)
    note=models.ForeignKey(Notes,on_delete=models.CASCADE,null=True, blank=True)

    def __str__(self):
         return str(self.note)

restapi_demo/apidemo/forms.py
"""
* Purpose:  Forms

* @author: Nikhil Lad
* @version: 3.7
* @since: 01-2-2019

"""
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.shortcuts import redirect
from image import settings
from requests import request
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from PIL import Image
from django import forms
from .models import Photo
from .cloud_services import s3_services

User= get_user_model()

class LoginForm(forms.ModelForm):
    model=User
    class Meta:
        fields=['username','password',]



class SignupForm(UserCreationForm):     # inheriting user-creation form to create form with following fields

    email=forms.RegexField(regex=r'^[_a-z0-9-]+(\.[_a-z0-9-]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,4})$',required=True)
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    def save(self, commit=True):
        user = super(SignupForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user

class loginForm(AuthenticationForm):     # inheriting user-creation form to create form with following fields
    class Meta:
        model = User
        fields = ('username','password')

    def save(self, commit=True):
        user = super(loginForm, self).save(commit=False)

        if commit:
            user.save()
        return user

class ImageUploadForm(forms.Form):
    image = forms.ImageField(label='Select a file')






class PhotoForm(forms.ModelForm):
    username = forms.CharField(required=True,label='Username',widget=forms.TextInput(attrs={'placeholder': 'Username '}))
    x = forms.FloatField(widget=forms.HiddenInput())
    y = forms.FloatField(widget=forms.HiddenInput())
    width = forms.FloatField(widget=forms.HiddenInput())
    height = forms.FloatField(widget=forms.HiddenInput())

    class Meta:
        model = Photo
        fields = ('file', 'x', 'y', 'width', 'height', )


    """ X coordinate, Y coordinate, height and width of the cropping box """

    def save(self):
        username = self.cleaned_data.get('username')    # username to save image for particular user.
        print('username-----------',username)
        photo = super(PhotoForm, self).save()

        x = self.cleaned_data.get('x')      # X coordinate
        y = self.cleaned_data.get('y')      # X coordinate
        w = self.cleaned_data.get('width')  # width of cropping box
        h = self.cleaned_data.get('height')  # height of cropping box

        # print(x,y,w,h)
        # print(photo)
        # print('taken measures ')
        image = Image.open(photo.file).convert('RGB')              # opens image file using Pillow library
        #print('take image object')
        #image.show()
        cropped_image = image.crop((x, y, w+x, h+y))        # crops image with x,y,w,h
        resized_image = cropped_image.resize((200, 200), Image.ANTIALIAS)  # resize cropped image.
        resized_image.save(photo.file.path)
        path=photo.file.path                    # gets the image path.
        s3_services.upload_image(request, path, username)      # calls method to upload pic to S3.


        return photo

    def clean_photo(self):
        #image_file = self.cleaned_data.get('photo')
        #super(PhotoForm, self)
        try:
            image_file = super(PhotoForm, self)
            if not image_file.name.endswith(".png",".jpeg",".jpg"):
                #raise forms.ValidationError("Only .jpeg image accepted")
                messages.error(request, 'Please select valid file')
                return redirect('photo_list')
            return image_file

        except Exception as e:
            print(e)
    # def clean_photo(self):
    #     photo = self.cleaned_data.get(['photo'])
    #     print('cleaned ',photo)
    #     if photo:
    #         print('in if loop')
    #         format = Image.open(photo.file).format
    #         print('format ',format)
    #         photo.file.seek(0)
    #         if format in settings.VALID_IMAGE_FILETYPES:
    #             return photo
    #     raise forms.ValidationError('error')

restapi_demo/apidemo/templates/acc_active_email.html
{% autoescape off %}
Hi {{ user.username }},
Please click on the link to confirm your registration,

http://{{ domain }}{% url 'activate' uidb64=uid token=token %}
{% endautoescape %}

restapi_demo/apidemo/templates/b.html
{% load static %}

<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Fundoo{% endblock %}</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">


    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <link href="{% static 'css/cropper.min.css' %}" rel="stylesheet">
  </head>
  <body>
    <div class="container">
      {% block content %}
      {% endblock %}
    </div>
    <script src="{% static 'JS/jquery-3.1.1.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'JS/cropper.min.js' %}"></script>
    {% block javascript %}
    {% endblock %}
  </body>
</html>

restapi_demo/apidemo/templates/base1.html
<!DOCTYPE html>
{% load static %}
<html>
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
     <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"
            integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>



    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <link href="{% static 'css/cropper.min.css' %}" rel="stylesheet">

    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">

    {% if title %}
    <title>Login-Page{{ title }}</title>
    {% else %}
    <title>Login-Page</title>
    {% endif %}
</head>
</head>
<body>

<main role="main" id="alert-msg" class="container">
    <div class="row">
        <div class="col-md-8">
            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-{{message.tags}}">
                {{ message }}
            </div>

            {% endfor %}
            {% endif %}
            {% block content %} {% endblock %}
        </div>
        <script src="{% static 'JS/jquery-3.1.1.min.js' %}"></script>
        <script src="{% static 'JS/bootstrap.min.js' %}"></script>
        <script src="{% static 'JS/cropper.min.js' %}"></script>
        {% block javascript %}
        {% endblock %}
    </div>
    </div>
</main>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
<script src="{% static 'JS/cropper.min.js' %}"></script>
</body>
</html>

restapi_demo/apidemo/templates/baseT.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}" />
    <link rel="stylesheet" type="text/css" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" />
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js" />
    <link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.bundle.min.js" />

    <meta charset="UTF-8">
    <title>Fundoo</title>
</head>
</html>

restapi_demo/apidemo/templates/dash_snippet.html
<html>
<head>
    <center> <h1>{% block title %} FundooAPP {% endblock %}</h1></center>
</head>



<body>
    <!--<main>-->
        <!--{% block content%}-->
        <!--<h1></h1>-->
        <!--{% endblock %}-->

</body>
</html>

restapi_demo/apidemo/templates/dashboard.html
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head>
{% block content %}
{% for c in token %}
<!--<h6>{{c}}</h6>-->
{% endfor %}
<!--<p>{{ token}}</p>-->

{% endblock %}
<script>
localStorage.setItem('token', ("{{token}}"));

</script>


<a href="{% url 'logout' %}" class="btn btn-warning" role="button" style="float: right;">Logout</a>
<center>
    <h2>Welcome</h2>
<!--{% if messages %}-->
<!--<p class="messages">-->
    <!--{% for message in messages %}-->
    <!--<p style="color:green;" {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>-->
    <!--{% endfor %}-->
<!--</p>-->
<!--{% endif %}-->
<h3 style="color:green;">{{ user.username }}</h3>

</center>
<!--<script>var username={{ user.username }}</script>-->

<title>Dashboard</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<body>
<!--<img src="https://s3.ap-south-1.amazonaws.com/fundoo/{{user.username }}.jpeg-->
<!--" alt="no pic to display"/>-->
<!-- Sidebar -->
<div class="w3-sidebar w3-bar-block" style="display:none" id="mySidebar">
  <button onclick="w3_close()" class="w3-bar-item w3-button w3-large">Close &times;</button>
  <a href="{% url 'profile_page' %}" class="w3-bar-item w3-button">Profile</a>
</div>

<!-- Page Content -->
<div class="w3-teal">
  <button class="w3-button w3-teal w3-xlarge" onclick="w3_open()">☰</button>
  <div class="w3-container">
    <h1>Fundoo</h1>
  </div>
</div>




<script>
function w3_open() {
  document.getElementById("mySidebar").style.width = "100%";
  document.getElementById("mySidebar").style.display = "block";
}

function w3_close() {
  document.getElementById("mySidebar").style.display = "none";
}
</script>

</body>
</html>

restapi_demo/apidemo/templates/file.html
{% load static %}

{% block content %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="myfile">
    <button type="submit">Upload</button>
  </form>

  {% if uploaded_file_url %}
    <p>File uploaded at: <a href="{{ uploaded_file_url }}">{{ uploaded_file_url }}</a></p>
  {% endif %}

  <p><a href="{% url 'home' %}">Return to home</a></p>
{% endblock %}

restapi_demo/apidemo/templates/fileupload.html
{% block content %}
<form method="post" enctype="multipart/form-data" action="{% url 'upload_profile' %}">
  <input type="file" name="pic" />
  <input type="submit" />
</form>
{% endblock %}

restapi_demo/apidemo/templates/index.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}" />
<link href='https://fonts.googleapis.com/css?family=Sofia' rel='stylesheet'>
<title>Index</title>
{#  Main HomePage contain links for login and registration #}
{% block content %}
<center>
    <h1>Welcome</h1><br><br>

    <b><a href="{% url 'signup' %}">Click Here to register !</a><br><br>
    <a href="{% url 'login_v' %}">Login</a><br><br>


</center>
{% endblock %}

restapi_demo/apidemo/templates/photo_list.html
{% extends 'b.html' %}

{% block javascript %}
<title>Fundoo Notes</title>
<script type="text/javascript">
    $("body").on("click", "#uploadbutton", function () {
        var allowedFiles = [".png"];
        var fileUpload = $("#fileUpload");
        var lblError = $("#lblError");
        var regex = new RegExp("([a-zA-Z0-9\s_\\.\-:])+(" + allowedFiles.join('|') + ")$");
        if (!regex.test(fileUpload.val().toLowerCase())) {
            lblError.html("Please upload files having extensions: <b>" + allowedFiles.join(', ') + "</b> only.");
            return false;
        }
        lblError.html('');
        return true;
    });
</script>

  <script>
    $(function () {

      /* SCRIPT TO OPEN THE MODAL WITH THE PREVIEW */
      $("#id_file").change(function () {
        if (this.files && this.files[0]) {
          var reader = new FileReader();
          reader.onload = function (e) {
            $("#image").attr("src", e.target.result);
            $("#modalCrop").modal("show");
          }
          reader.readAsDataURL(this.files[0]);
        }
      });

      /* SCRIPTS TO HANDLE THE CROPPER BOX */
      var $image = $("#image");
      var cropBoxData;
      var canvasData;
      $("#modalCrop").on("shown.bs.modal", function () {
        $image.cropper({
          viewMode: 1,
          aspectRatio: 1/1,
          minCropBoxWidth: 150,
          minCropBoxHeight: 150,
          ready: function () {
            $image.cropper("setCanvasData", canvasData);
            $image.cropper("setCropBoxData", cropBoxData);
          }
        });
      }).on("hidden.bs.modal", function () {
        cropBoxData = $image.cropper("getCropBoxData");
        canvasData = $image.cropper("getCanvasData");
        $image.cropper("destroy");
      });

      $(".js-zoom-in").click(function () {
        $image.cropper("zoom", 0.1);
      });

      $(".js-zoom-out").click(function () {
        $image.cropper("zoom", -0.1);
      });

      /* SCRIPT TO COLLECT THE DATA AND POST TO THE SERVER */
      $(".js-crop-and-upload").click(function () {
        var cropData = $image.cropper("getData");
        $("#id_x").val(cropData["x"]);
        $("#id_y").val(cropData["y"]);
        $("#id_height").val(cropData["height"]);
        $("#id_width").val(cropData["width"]);
        $("#formUpload").submit();



      });

    });
  </script>

{% endblock %}

{% block content %}

<a href="{% url 'base' %}" class="btn btn-default">Home</a></p><br>
 <img src="https://s3.ap-south-1.amazonaws.com/fundoo/{{ user.username }}
" alt="no pic to display"/><br>
  <h1 class="page-header"></h1>

  <!-- FORM TO UPLOAD THE IMAGES -->
<form method="post" enctype="multipart/form-data" id="formUpload">
    {% csrf_token %}
    <!--{{ form }}-->
  {% for field in form %}

<p>{{ field }}</p>
{% endfor %}
</form><a href="{% url 'delete_from_s3' %}" class="btn btn-default">Remove photo</a></p><br>

  <!-- MODAL TO CROP THE IMAGE -->

<form enctype="multipart/form-data" action="{% url 'photo_list' %}" method="post" >
<div class="modal fade" id="modalCrop">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <h4 class="modal-title">Crop the photo</h4>
        </div>
        <div class="modal-body">
          <img src="" id="image" style="max-width: 100%;">
        </div>
        <div class="modal-footer">
          <div class="btn-group pull-left" role="group">
            <button type="button" class="btn btn-default js-zoom-in">
              <span class="glyphicon glyphicon-zoom-in"></span>
            </button>
            <button type="button" class="btn btn-default js-zoom-out">
              <span class="glyphicon glyphicon-zoom-out"></span>
            </button>
          </div>
          <button type="button" class="btn btn-default" data-dismiss="modal">Nevermind</button>
          <button type="button" class="btn btn-primary js-crop-and-upload" id="uploadbutton">Crop and upload</button>
        </div>
      </div>
    </div>
  </div>
</form>

<div class="col-md-6">
  <label>User name</label>
</div>
<div class="col-md-5"><p>{{ user.username }}</p>
</div>
<div class="col-md-6">
  <label>Email Id</label>
</div>
<div class="col-md-5"><p>{{ user.email }}</p>
</div>
{% endblock %}

restapi_demo/apidemo/templates/registration.html
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script>
$('#password, #confirm_password').on('keyup', function () {
  if ($('#password').val() == $('#confirm_password').val()) {
    $('#message').html('Matching').css('color', 'green');
  } else
    $('#message').html('Not Matching').css('color', 'red');
});
$.ajax({

})

</script>
{% block content %}

<form  method="POST">{% csrf_token %}


    <!--username: <input type="text" id="uname">-->
    <!--pass:   <input type="password" id="pass">-->
    <!--confirm pass : <input type="password" id="cpass">-->
    {{ form.as_p }}
    <input type="submit" value="Submit" id="submit" />
</form>
{% endblock %}